version: '3.7'

services:
  user-mongo-db:
    container_name: user-mongo-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/docker-entrypoint-initdb.d/mongo-user-init.sh:/docker-entrypoint-initdb.d/mongo-user-init.sh
      - user-mongo-db:/data/db
      - user-mongo-config:/data/configdb
    networks:
      - user-network
    env_file:
      - .env.dev
    restart:
      always
    environment:
      MONGO_INITDB_DATABASE: ${DEFAULT_MONGO_INITDB_ROOT_DB}
      MONGO_INITDB_ROOT_USERNAME: ${DEFAULT_MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DEFAULT_MONGO_INITDB_ROOT_PASSWORD}
      USER_SERVICE_MONGO_DATABASE_NAME: ${USER_SERVICE_MONGO_DATABASE_NAME}
      USER_SERVICE_MONGO_DATABASE_USER: ${USER_SERVICE_MONGO_DATABASE_USER}
      USER_SERVICE_MONGO_DATABASE_PASSWORD: ${USER_SERVICE_MONGO_DATABASE_PASSWORD}

  user-service:
    container_name: user-service
    build:
      context: ./user-service
      args:
        ENV_PROFILE: ${USER_SERVICE_ENV_PROFILE}
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - user-network
    restart:
      on-failure
    depends_on:
      - user-mongo-db
    env_file:
      - .env.dev
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${USER_SERVICE_MONGO_DATABASE_USER}:${USER_SERVICE_MONGO_DATABASE_PASSWORD}@user-mongo-db
      SPRING_DATA_MONGODB_DATABASE: ${USER_SERVICE_MONGO_DATABASE_NAME}
      SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE: ${DEFAULT_MONGO_INITDB_ROOT_DB}

volumes:
  user-mongo-db:
  user-mongo-config:

networks:
  user-network: