spring:
  profiles:
    active: "dev"
  jackson:
    serialization:
      indent_output: true

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: ${EXPENSE_SPRING_DATA_MONGODB_URI}
      database: ${EXPENSE_SPRING_DATA_MONGODB_DATABASE}
      authentication-database: ${EXPENSE_SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE}

expense-service:
  limit: ${EXPENSE_LIMIT}
  rabbitmq:
    user:
      creation-queue: user-creation-queue
      exchange: user-creation-exchange
      routingkey: user-create
    invoice:
      validation-queue: invoice-validation-queue
      exchange: invoice-validation-exchange
      routingkey: invoice-validate

server:
  port: 8082