spring:
  profiles:
    active: "dev"
  jackson:
    serialization:
      indent_output: true

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: ${USER_SPRING_DATA_MONGODB_URI}
      database: ${USER_SPRING_DATA_MONGODB_DATABASE}
      authentication-database: ${USER_SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

user-service:
  rabbitmq:
    producer:
      user:
        creation-queue: user-creation-queue
        exchange: user-creation-exchange
        routingkey: user-create
      expense:
        validation-queue: expense-validation-queue
        exchange: expense-validation-exchange
        routingkey: expense-validate
    consumer:
      invoice:
        validation-queue: user-validation-queue
        exchange: user-validation-exchange
        routingkey: user-validate

server:
  port: 8081