spring:
  profiles:
    active: "dev"
  jackson:
    serialization:
      indent_output: true

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: ${USER_SPRING_DATA_MONGODB_URI}
      database: ${USER_SPRING_DATA_MONGODB_DATABASE}
      authentication-database: ${USER_SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE}

server:
  port: 8081