spring:
  profiles:
    active: "dev"
  jackson:
    serialization:
      indent_output: true

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: ${INVOICE_SPRING_DATA_MONGODB_URI}
      database: ${INVOICE_SPRING_DATA_MONGODB_DATABASE}
      authentication-database: ${INVOICE_SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

invoice-service:
  rabbitmq:
    producer:
      user:
        validation-queue: user-validation-queue
        exchange: user-validation-exchange
        routingkey: user-validate
    consumer:
      expense:
        validation-queue: invoice-validation-queue
        exchange: invoice-validation-exchange
        routingkey: invoice-validate

server:
  port: 8083